<?php
/**
 * @var $block \HighQDev\Core\Block\Index
 */
?>

<?php
if ($block->isCustomerLoggedIn()) {
    //Display Customer Name(Firstname + Lastname) and Email
    echo "Registered Customer";
    echo "<br>";
    $_result = $block->getCustomer();
    echo $_result['name'];
    echo "<br>";
    echo $_result['email'];
    echo $block->getCMSBlock();
} else {
    echo "This is a Guest Customer";
}

?>

