<?php
/**
 * @var $block \HighQDev\Core\Block\Index
 */
?>

<?php
if ($block->isCustomerLoggedIn()) {
    //Display Customer Name(Firstname + Lastname) and Email
    echo "Registered Customer";
    echo "<br>";
    $_result = $block->getCustomer();
    echo $_result['name'];
    echo "<br>";
    echo $_result['email'];
} else {
    echo "This is a Guest Customer";
}

?>
<table>
    <tr>
        <th>Id</th>
        <th>SKU</th>
        <th>Comment</th>
        <th>Approved</th>
    </tr>
    <?php
    $collection = $block->getResult();
    foreach ($collection as $item) {
        ?>
        <tr>
            <td><?php echo $item->getEntityId();; ?></td>
            <td><?php echo $item->getSku(); ?></td>
            <td><?php echo $item->getComment(); ?></td>
            <td><?php echo $item->getApproved(); ?></td>
        </tr>
    <?php } ?>
</table>
